apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  pg-username: {{ .Values.auth.username | b64enc | quote }}
  pg-password: {{ .Values.auth.password | b64enc | quote }}
  pg-database: {{ .Values.auth.database | b64enc | quote }}
