apiVersion: v1
kind: Service
metadata:
  name: mock-push-service
  namespace: local-stack
  labels:
    app: mock-push
spec:
  type: NodePort
  selector:
    app: mock-push
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30083
