{{- if .Values.nodePort.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin.fullname" . }}-nodeport
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.nodePort.port }}
      protocol: TCP
      name: pgadmin
  selector:
    {{- include "pgadmin.selectorLabels" . | nindent 4 }}
{{- end }}
