apiVersion: v1
kind: Service
metadata:
  name: aisecurity-mgmt-service-service
  namespace: local-stack
  labels:
    app: aisecurity-mgmt-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: aisecurity-mgmt-service